import { AgentInput, AgentOutput, WorkflowStep } from '@/packages/shared/types';
import { AutomationAgentOutputSchema } from '@/packages/shared/schemas';

export class AutomationAgent {
  public static readonly agentName = 'Automation Agent';
  public static readonly role = 'Automation Engineer ("Automation Engineer")';

  /**
   * Generates production-ready automation workflows and script artifacts.
   */
  public static async execute(input: AgentInput): Promise<AgentOutput> {
    const { processId } = input;

    const steps: WorkflowStep[] = [
      {
        id: 'wf_step_1',
        name: 'Ingest Webhook',
        type: 'api_call',
        target: 'Shopify Store',
        action: 'POST /api/webhooks/shopify/orders/create',
        method: 'api',
      },
      {
        id: 'wf_step_2',
        name: 'Validate Fraud & Risk Score',
        type: 'api_call',
        target: 'Shopify Store',
        action: 'GET /admin/api/orders/{id}/risks.json',
        method: 'api',
      },
      {
        id: 'wf_step_3',
        name: 'Verify Stripe Charge',
        type: 'api_call',
        target: 'Stripe Payments',
        action: 'GET /v1/payment_intents/{id}',
        method: 'api',
      },
      {
        id: 'wf_step_4',
        name: 'Generate QuickBooks Invoice',
        type: 'api_call',
        target: 'QuickBooks Online',
        action: 'POST /v3/company/invoice',
        method: 'api',
      },
      {
        id: 'wf_step_5',
        name: 'Append Google Sheet Row',
        type: 'api_call',
        target: 'Google Sheets',
        action: 'POST /v4/spreadsheets/{id}/values:append',
        method: 'api',
      },
      {
        id: 'wf_step_6',
        name: 'Send Customer Confirmation Email',
        type: 'api_call',
        target: 'SendGrid Email API',
        action: 'POST /v3/mail/send',
        method: 'api',
      },
    ];

    const executableScript = `/**
 * QuickCart Automated Order Processing Runner
 * Generated by ProcessMind Automation Agent
 * Verified in Sandbox by ProcessMind Verification Agent
 */
import { shopify, stripe, quickbooks, sheets, sendgrid } from '@processmind/connectors';

export async function processQuickCartOrder(event: { orderId: string; paymentIntentId: string }) {
  console.log('[ProcessMind] Starting order fulfillment pipeline for Order #' + event.orderId);
  
  // 1. Fetch Order details from Shopify API
  const order = await shopify.getOrder(event.orderId);
  console.log('[Shopify API] Order retrieved:', order.id, 'Customer:', order.customer.email);
  
  // 2. Risk check
  const risks = await shopify.getOrderRisks(event.orderId);
  if (risks.recommendation === 'cancel') {
    throw new Error('High risk order flagged by Shopify: ' + risks.summary);
  }
  
  // 3. Confirm Stripe charge
  const payment = await stripe.paymentIntents.retrieve(event.paymentIntentId);
  if (payment.status !== 'succeeded') {
    throw new Error('Payment capture unverified: ' + payment.status);
  }
  
  // 4. QuickBooks Invoice
  const invoice = await quickbooks.createInvoice({
    customer: order.customer.name,
    items: order.line_items,
    total: payment.amount_received / 100
  });
  console.log('[QuickBooks API] Invoice generated:', invoice.docNumber);
  
  // 5. Append to Google Sheets ledger
  await sheets.appendRow({
    spreadsheetId: process.env.ORDERS_SHEET_ID,
    row: [new Date().toISOString(), order.id, order.customer.name, invoice.total, 'COMPLETED']
  });
  
  // 6. SendGrid notification
  await sendgrid.send({
    to: order.customer.email,
    template: 'order-confirmed',
    data: { orderId: order.id, invoiceUrl: invoice.pdfUrl }
  });
  
  return { success: true, orderId: order.id, invoiceId: invoice.id };
}`;

    const structuredData = {
      workflowName: 'QuickCart Order Processing Automation',
      steps,
      requiresHumanApproval: true,
      executableScript,
      estimatedExecutionTimeSec: 1.4,
    };

    AutomationAgentOutputSchema.parse(structuredData);

    return {
      status: 'success',
      summary: `Automation Agent formulated a 6-step end-to-end automation plan. Generated validated TypeScript workflow code. Awaiting Owner Approval gate before production deployment.`,
      structuredData,
      evidenceRefs: steps.map(s => s.id),
      warnings: ['Requires Small Business Owner manual approval prior to live execution (Section 28 Security).'],
      nextAction: 'AWAITING_APPROVAL',
    };
  }
}
